services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend/uploads:/uploads
    depends_on:
      - backend


  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - model


  model:
    build:
      context: ./model
    ports:
      - "5002:5002"