services:
  frontend:
    build:
      context: ./frontend
    networks:
      - appnetwork
    ports:
      - "5000:5000"
    depends_on:
      - backend


  backend:
    build:
      context: ./backend
    networks:
      - appnetwork
    ports:
      - "5001:5001"
    depends_on:
      - model


  model:
    build:
      context: ./model
    networks:
      - appnetwork
    ports:
      - "5002:5002"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

networks:
  appnetwork:
    driver: bridge
