services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend/uploads:/uploads
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5001"
    networks:
      - app_network
    depends_on:
      - model

  model:
    build:
      context: ./model
    ports:
      - "5002"
    networks:
      - app_network